import * as Card from "./card"

export type Cards<T> = Record<Card.Card, T>

export const empty: Cards<0> = {
  ManeuverLeft: 0,
  ManeuverRight: 0,
  ManeuverForward: 0,
  AssaultLeft: 0,
  AssaultRight: 0,
  AssaultForward: 0,
  Charge: 0,
  FlankLeft: 0,
  FlankRight: 0,
  Hoplite: 0,
  Polis: 0,
  Koinas: 0,
  HellenicCraftsmen: 0,
  MilitaryReforms: 0,
  OracleOfDelphi: 0,
  PoliticalReforms: 0,
  TempleOfAthena: 0,
  TempleOfPoseidon: 0,
  TempleOfZeus: 0,
  OrganizedDeploy: 0,
  MilitaryMobilization: 0,
  AuxiliaryTroops: 0,
  Phalanx: 0,
  DemocraticFaction: 0,
  AgeanSea: 0,
  IonianSea: 0,
  Hellespont: 0,
  Forage: 0,
  Psiloi: 0,
  TheSenate: 0,
  TheFiveEphors: 0,
  TheTenStrategoi: 0,
  Provisions: 0,
  SupplyCache: 0,
  PersianSupport: 0,
  MilitaryTraining: 0,
  MilitaryLogistics: 0,
  ThraticanTactics: 0,
  OligarchicFaction: 0,
  VillageGranary: 0,
  WarSpoils: 0,
}
